In [1]:
import pandas as pd

In [4]:
reader = pd.read_csv("../csv/compare_callResultAI.csv")

In [7]:
reader

name           Criterion Name   
0    1684482083958_3770_810983451276_516462765.mp3  Contain all information  \
1    1684482109334_3771_810932104194_516462776.mp3  Contain all information   
2    1684484668825_3776_810365496726_516470077.mp3  Contain all information   
3    1684484804994_3753_810989015916_516470478.mp3  Contain all information   
4    1684485272349_3648_810939424196_516471469.mp3  Contain all information   
..                                             ...                      ...   
295  1686275888826_3729_810973322412_519911491.mp3  Contain all information   
296  1686276029433_3734_810981456551_519912816.mp3  Contain all information   
297  1686279460634_3732_810909757150_519942265.mp3  Contain all information   
298  1686285301787_3769_810337445113_519982400.mp3  Contain all information   
299  1686296155875_3755_810349533873_525039757.mp3  Contain all information   

    Expected Result Actual Result callResultAI  
0                no           NaN        nopay  
1                no            No        nopay  
2                no           NaN        nopay  
3                no           NaN      willpay  
4                no           NaN    undefined  
..              ...           ...          ...  
295             yes           Yes    undefined  
296             yes           Yes      willpay  
297              no           NaN      willpay  
298              no           NaN        nopay  
299              no           NaN        nopay  

[300 rows x 5 columns]

### Call willpay

In [9]:
df_call_willpay = reader[reader['callResultAI'] == 'willpay']
df_call_willpay

name           Criterion Name   
3    1684484804994_3753_810989015916_516470478.mp3  Contain all information  \
6    1684485812724_3773_810974045098_516473273.mp3  Contain all information   
7    1684485817887_3776_810985709404_521499073.mp3  Contain all information   
8    1684487078116_3466_850943236969_516475928.mp3  Contain all information   
9    1684543230203_3699_810982605030_516482740.mp3  Contain all information   
..                                             ...                      ...   
292  1686274919328_3731_810705997856_524930479.mp3  Contain all information   
293  1686274919345_3731_810705997856_519903401.mp3  Contain all information   
294  1686275705515_3733_810777991931_519910172.mp3  Contain all information   
296  1686276029433_3734_810981456551_519912816.mp3  Contain all information   
297  1686279460634_3732_810909757150_519942265.mp3  Contain all information   

    Expected Result Actual Result callResultAI  
3                no           NaN      willpay  
6                no           Yes      willpay  
7                no     Partially      willpay  
8                no           NaN      willpay  
9                no           NaN      willpay  
..              ...           ...          ...  
292              no           NaN      willpay  
293              no           NaN      willpay  
294             yes            No      willpay  
296             yes           Yes      willpay  
297              no           NaN      willpay  

[152 rows x 5 columns]

In [10]:
import numpy as np

In [18]:
A = np.random.randn(4, 3)
B = np.random.randn(3, 5)
C = np.dot(A, B)
print(C)

[[ 0.5354411  -2.81150526 -0.20141029 -1.31802803 -0.05530885]
 [ 0.35214436  0.69203871 -0.05170757 -0.55048953 -0.22270346]
 [-1.04484322  0.64184737  0.29021594  2.21143199 -2.48297798]
 [-0.06853224  0.55705251  0.04630083  0.2608534  -0.82853828]]
